### ISSUE TITLE
parameter `FracModPerProt`

### ISSUE THREAD

**Issue by mlocardpaulet** [veitveit/PhosFake#4]
Here is the yaml definition or the parameter:
```
FracModPerProt:
    group: "Ground Truth Data"
    type: "paramGroundTruth"
    description: "Factor for generating more proteoforms from selected proteins."
    min: 0
    max: 5
    default: 0
```
I don't think that the description is very clear. Also, it is not very logical to call it "FracMod" with "Frac" for "fraction" and have a parameter ranging from 0 to 5. Is it correct?
